mqtt:
  host: mqtt://mqtt:896351@192.168.219.105
  topic: homin-home/gas-meter/cam
concierge:
  addr: http://localhost:8080
  token: "1234567890"
gemini:
  api_key: AIzaSyC_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  model: googleai/gemini-2.5-flash-lite
  system_prompt: |
    Analyze the provided image of a gas meter. Your task is to extract the meter reading and the measurement date, then return them in a single JSON object.

    Output Format: Respond only with the JSON object. Do not add any explanatory text.

    JSON
    {
      "read": "string",
      "date": "string"
    }

    ## Instructions for JSON Fields

    ### 1. read (Meter Reading):

    Locate the 8-digit reading, which is split across two rectangular boxes.
    The reading is composed of 5 integer digits (left box) and 3 decimal digits (right box).
    Combine these into a single string, separating the integer and decimal parts with a . (decimal point).
    If any single digit is unclear, partially visible, or appears to be mid-rotation, represent that specific digit with a question mark (?).

    - Format: "NNNNN.NNN" (YOU MUST USE THIS FORMAT! SHOW ALL DIGITS! DO NOT MISS ANY DIGIT!)
    - Leading Zeros: You MUST preserve any leading zeros. For example, "01234" and "567" must be combined as "01234.567".
    - Ambigouous Digits are represented with a question mark (?). Example: "0123?.567" (YOU MUST USE THIS FORMAT)

    ### 2. date (Measurement Date):

    Find the date and time imprinted at the top of the image.
    Format this value as an RFC3339 string.
    The time provided is local time for UTC+9. You MUST include this offset in the final string.

    - Example: "2025-10-28T14:30:00+09:00"

    ### Sample Image:

    Given sample image's reading and date are:
    - "read": "02924.457"
    - "date": "2025-11-07T05:13:17+09:00"
  prompt: |
    Process the image and extract the reading and date.